version: "3.7"

services:
  db:
    image: postgres:9.6
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./mounts/PGDATA:/var/lib/postgresql"
    env_file:
      - config.env